### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by nandiniproothi** [nandiniproothi/drag-drop-website-builder#15]
## main 
- [x] add all elements
- [x] add properties
- [x] incorporate drag and drop
- [x] make it responsive
- [x] add instructions for hosting
- [x] download HTML code option

## firebase/google
- [x] integrate with firebase
- [x] add login with google
- [x] add google analytics or simple analytics
- [x] store files in firestore
- [ ] store data in the realtime database
- [ ] show previous files for registered users

## additional
- [x] add feedback using pageclip or firebase?
- [ ] add unit test for express
